### ISSUE TITLE
可以赞助域名和网站

### ISSUE THREAD

**Issue by emptymalei** [uupers/uupers.github.io#1]
1. 域名例如 uupers.com 我可以赞助你们啊
2. 网站如果不介意我可以给你们用 jekyll 搭一个，不过要你们定设计稿

**Comment by LePtC** [comment]
大佬上线了！ ⊙ω⊙
主要是觉得 README 看着就挺好，就暂时没做网站…
等我跟大家商量一下设计网站的事再联系你哦 o(*≧▽≦)ツ
（你想进群跟我们一块讨论也欢迎哦）

**Comment by emptymalei** [comment]
不是大佬 😱 

嗯嗯，readme 也挺好的。

对了，我说的域名是说我给你们买域名的钱，你们自己去买，这样你们自己改 dns  ~~

----

捐了100块你们可以买域名了。

**Comment by LePtC** [comment]
感谢捐赠 ❤️  等我们的网站上线后会再给你发消息的～
如果你想加入组织（比如看看 Daily Idea 提提建议啥的）我们也欢迎～
