### ISSUE TITLE
哔站公共号的绑定手机号问题

### ISSUE THREAD

**Issue by LePtC** [uupers/uupers.github.io#4]
开设哔站公共号需要有一个绑定手机号，但大家的手机号都已经绑定各自的帐号了，大家对这个问题有什么好的解决方案？

**Comment by LePtC** [comment]
另外关于抢个好的 mid 号我觉得不用想了，我发现哔站仅昨天一天就有三十万新用户被注册（[297000000](http://space.bilibili.com/297000000/)-[297300000](http://space.bilibili.com/297300000/)），平均每秒就刷过去三四个，目测都是机器干的（用户名都是无意义的字母数字组合，零关注零动态）

![default](https://user-images.githubusercontent.com/6371171/36915126-8174f218-1e47-11e8-81ad-7776e7f4028d.png)

心疼哔站服务器一秒 2333

---
Update：后来又思考了一下，其实只是最后一两位不能控制，中间的几位是完全可以控制的，比如如果再等上几天（3月12号左右）就可能注册到 3000000XX 这样的号

如果大家感兴趣的话就组织大家抢一下，没人感兴趣就算了，一个人抢的成功率太低了  ╮(╯_╰)╭

**Comment by emptymalei** [comment]
用 Google Voice 的号码可以的。
我 B 站绑定的是美国的手机号，我还有个国内的手机号，但是我觉得绑定私人的手机号不太好，所以可以试试用 Google Voice 的虚拟号码。

https://voice.google.com

**Comment by LePtC** [comment]
emmmm 用不了啊？

![default](https://user-images.githubusercontent.com/6371171/36921573-b5c5a3fe-1e5c-11e8-85c8-b3eb8ef9bf3c.png)

**Comment by emptymalei** [comment]
奇怪啊
![image](https://user-images.githubusercontent.com/663798/36922198-49643438-1e24-11e8-8513-94dba4364759.png)
我能用

**Comment by LePtC** [comment]
我翻出来一个几年前用 QQ 邮箱注册的号：https://space.bilibili.com/43419575/ （注册之后一次也没用过）
然后试了下用法国的手机号绑定，发现可以
但这么搞有一个问题，我半年后就回国了，这个手机号会被回收，到时候可能会有新的麻烦

**Comment by A0nameless0man** [comment]
我有个副卡，应该可以。

**Comment by LePtC** [comment]
没问题了，目前是用的 `yxlllc` 家长的手机号
